EC-TH2012-J/Models/Sanphamcanmua.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC_TH2012_J.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    
    public partial class Sanphamcanmua
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sanphamcanmua()
        {
            this.DanhsachdangkisanphamNCCs = new HashSet<DanhsachdangkisanphamNCC>();
        }
    
        public int ID { get; set; }
        public string MaSP { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<System.DateTime> Ngayketthuc { get; set; }
        public Nullable<System.DateTime> Ngaydang { get; set; }

        [AllowHtml]
        public string Mota { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhsachdangkisanphamNCC> DanhsachdangkisanphamNCCs { get; set; }
    }
}

EC-TH2012-J/Controllers/B2B/SanPhamCanMuaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using EC_TH2012_J.Models;
using EC_TH2012_J.Models.B2B;

namespace EC_TH2012_J.Controllers.B2B
{
    public class SanPhamCanMuaController : Controller
    {
        //
        // GET: /SanPhamCanMua/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult TimSPCM(string key, int? page)
        {
            SanphamcanmuaModel spcm = new SanphamcanmuaModel();
            ViewBag.key = key;
            return PhanTrangSPCM(spcm.TimSPCM(key), page, null);
        }

        public ActionResult DeleteSPCM(int id)
        {
            SanphamcanmuaModel ncc = new SanphamcanmuaModel();
            if (ncc.getSanphamcanmua(id) == null)
            {
                return HttpNotFound();
            }
            ncc.DeleteSPCM(id);
            return TimSPCM(null, null);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ThemSPCM(SanPhamCanMuaAdd loai)
        {

            if (ModelState.IsValid)
            {
                SanphamcanmuaModel ncc = new SanphamcanmuaModel();               
                ncc.ThemSPCM(GetData(loai));
                return View("Index");
            }
            return View("Index", loai);
        }

        public ActionResult EditSPCM(int id)
        {
            SanphamcanmuaModel sp = new SanphamcanmuaModel();
            var s = sp.getSanphamcanmua(id);
            SanPhamCanMuaEdit model = new SanPhamCanMuaEdit();
            model.ID = s.ID;
            model.Mota = s.Mota;
            model.Ngayketthuc = s.Ngayketthuc;
            model.Soluong = s.Soluong;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditSPCM(SanPhamCanMuaEdit loai)
        {

            if (ModelState.IsValid)
            {
                SanphamcanmuaModel ncc = new SanphamcanmuaModel();
                ncc.EditSPCM(loai);
                return RedirectToAction("Index");
            }
            return RedirectToAction("EditSPCM", loai.ID);
        }


        private Sanphamcanmua GetData(SanPhamCanMuaAdd loai)
        {
            Sanphamcanmua sp = new Sanphamcanmua();
            sp.MaSP = loai.MaSP;
            sp.Ngayketthuc = loai.Ngayketthuc;
            sp.Mota = loai.Mota;
            sp.Soluong = loai.Soluong;
            return sp;
        }

        [HttpPost]
        public ActionResult MultibleDel(List<string> lstdel)
        {
            foreach (var item in lstdel)
            {
                SanphamcanmuaModel ncc = new SanphamcanmuaModel();
                ncc.DeleteSPCM(Convert.ToInt32(item));
            }
            return TimSPCM(null, null);
        }

        public ActionResult PhanTrangSPCM(IQueryable<Sanphamcanmua> lst, int? page, int? pagesize)
        {
            int pageSize = (pagesize ?? 10);
            int pageNumber = (page ?? 1);
            return PartialView("SPCMPartial", lst.OrderByDescending(m => m.Ngaydang).ToPagedList(pageNumber, pageSize));
        }
	}
}

EC-TH2012-J/Views/SanPhamCanMua/EditSPCM.cshtml
@model EC_TH2012_J.Models.SanPhamCanMuaEdit
@{
    ViewBag.Title = "Sửa thông tin Sản phẩm cần mua";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<script src="~/ckeditor/ckeditor.js"></script>
<div class="row">
    <h1>@ViewBag.tensp</h1>
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2><i class="glyphicon glyphicon-user"></i>@ViewBag.Title</h2>
                <div class="box-icon">
                    <a href="#" class="btn btn-setting btn-round btn-default"><i class="glyphicon glyphicon-cog"></i></a>
                    <a href="#" class="btn btn-minimize btn-round btn-default">
                        <i class="glyphicon glyphicon-chevron-up"></i>
                    </a>
                    <a href="#" class="btn btn-close btn-round btn-default"><i class="glyphicon glyphicon-remove"></i></a>
                </div>
            </div>
            <div class="box-content">
                @using (Html.BeginForm("EditSPCM", "SanPhamCanMua", FormMethod.Post, new { id = "sualoaisp", autocomplete = "off" }))
                {

                    <div class="form-horizontal">
                        <div class="alert alert-info" style="display:none">
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary()
                            <span id="kiemtratrung"></span>
                        </div>
                        @Html.HiddenFor(model => model.ID)
                        <div class="form-group">
                            @Html.LabelFor(model => model.Soluong, new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.EditorFor(model => model.Soluong, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Soluong)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Ngayketthuc, new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.EditorFor(model => model.Ngayketthuc, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Ngayketthuc)
                            </div>
                        </div>


                        <div class="form-group">
                            @Html.LabelFor(model => model.Mota, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.Mota, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Mota)
                                <script>
                                    CKEDITOR.replace('Mota');
                                </script>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <a class="btn btn-info" href='javascript: submitform("sualoaisp")'>
                                    <i class="glyphicon glyphicon-wrench icon-white"></i>
                                    Cập nhật
                                </a>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <!--/span-->
</div><!--/row-->

EC-TH2012-J/Views/SanPhamCanMua/Index.cshtml
@model EC_TH2012_J.Models.SanPhamCanMuaAdd
@{
    ViewBag.Title = "Sản phẩm cần mua";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<script src="~/ckeditor/ckeditor.js"></script>

<script>
    function GetAliasDetails() {
        var text = $('#sanpham').val();
        if (text != '') {
            $("#divLoader").show();
            $.ajax({
                type: "POST",
                contentType: "application/json; charset=utf-8",
                url: "@Url.Action("SearchByName", "Search")",
                data: "{term:'" + text + "'}",
            dataType: "json",
            success: function (data) {
                if (data != null) {
                    var html = "<div style=\"border:3px solid #c6c6c6;background-color: #fff;\">";
                    html += "<table>";
                    $.each(data, function (i, item) {
                        html += "<tbody class=\"hoversearch\"  onclick=\"updategiatri(\'" + item.MaSP + "\')\"><tr>";
                        html += "<td style=\"padding:5px\" rowspan=\"2\"><img width=\"50\" height=\"50\" src=\"@Url.Content("~/images/products/")" + item.AnhDaiDien + "\" /></td>"
                        html += "<td style=\"padding:5px\"><span class=\"bold\">" + item.TenSP + "</span></td></tr>";
                        html += "<tr><td style=\"padding:5px\"><span style=\"color:#2A1051\" class=\"bold\">" + item.GiaTien.toLocaleString() + " VNĐ</span></td></tr>"
                        html += "</tbody>"
                    })
                    html += "</table></div>";
                    $("#divAutoComplete").html(html).show(500);
                }
            },
            error: function (result) {
                $("#divLoader").hide();
            }
        });
    }
    else {
            close();
    }
    }


    function close() {
        $("#divAutoComplete").html('');
        $("#divAutoComplete").slideUp(1000);
        $("#divLoader").hide();
    }

    function updategiatri(val)
    {
        $('#sanpham').val(val);
        $("#divAutoComplete").hide(500);
    }
</script>
<style>
    .hoversearch {
        cursor: pointer;
        border-bottom: 1px dotted #c6c6c6;
    }

        .hoversearch:hover {
            background-color: #e8e8e8;
        }
</style>


<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2><i class="glyphicon glyphicon-user"></i>@ViewBag.Title</h2>
                <div class="box-icon">
                    <a href="#" class="btn btn-setting btn-round btn-default"><i class="glyphicon glyphicon-cog"></i></a>
                    <a href="#" class="btn btn-minimize btn-round btn-default">
                        <i class="glyphicon glyphicon-chevron-up"></i>
                    </a>
                    <a href="#" class="btn btn-close btn-round btn-default"><i class="glyphicon glyphicon-remove"></i></a>
                </div>
            </div>
            <div class="box-content">
                <div class="alert alert-info" id="alert-info" style="display:none"></div>
                <div class="form-inline" style="text-align: right; padding: 10px">

                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-search red"></i></span>
                        <input id="tensp" type="text" class="form-control" placeholder="Tên sản phẩm" oninput="timkiemspcm()">
                    </div>
                    <div class="input-group">
                        <a class="btn btn-danger" href='javascript:multibledel("@Url.Action("MultibleDel", "SanPhamCanMua")")'>
                            <i class="glyphicon glyphicon-trash icon-white"></i>
                            Xóa các sản phẩm đã chọn
                        </a>
                    </div>

                </div>
                <div class="Ajax-Table">
                    @Html.Action("TimSPCM", "SanPhamCanMua")
                </div>

            </div>
        </div>
    </div>
    <!--/span-->
</div><!--/row-->

<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2><i class="glyphicon glyphicon-user"></i>Thêm @ViewBag.Title</h2>
                <div class="box-icon">
                    <a href="#" class="btn btn-setting btn-round btn-default"><i class="glyphicon glyphicon-cog"></i></a>
                    <a href="#" class="btn btn-minimize btn-round btn-default">
                        <i class="glyphicon glyphicon-chevron-up"></i>
                    </a>
                    <a href="#" class="btn btn-close btn-round btn-default"><i class="glyphicon glyphicon-remove"></i></a>
                </div>
            </div>
            <div class="box-content">

                @using (Html.BeginForm("ThemSPCM", "SanPhamCanMua", FormMethod.Post, new { autocomplete = "off", enctype = "multipart/form-data" }))
                {

                    <div class="form-horizontal">
                        <div class="alert alert-info" style="display:none">
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary()
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.MaSP, new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.TextBoxFor(model => model.MaSP, new { @class = "form-control", id = "sanpham", oninput = "GetAliasDetails()" })
                                @Html.ValidationMessageFor(model => model.MaSP)
                                <div id="divAutoComplete" style="position:absolute; z-index:100; padding-top: 10px">
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Soluong, new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.EditorFor(model => model.Soluong, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Soluong)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Ngayketthuc, new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.EditorFor(model => model.Ngayketthuc, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Ngayketthuc)
                            </div>
                        </div>

                        
                        <div class="form-group">
                            @Html.LabelFor(model => model.Mota, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.Mota, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Mota)
                                <script>
                                    CKEDITOR.replace('Mota');
                                </script>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Thêm mới" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }

            </div>

        </div>
    </div>
    <!--/span-->
</div><!--/row-->

EC-TH2012-J/Views/SanPhamCanMua/SPCMPartial.cshtml
@using EC_TH2012_J.Models;
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<Sanphamcanmua>


<table class="table table-striped table-bordered bootstrap-datatable datatable responsive">
    <thead>
        <tr>
            <th>
                <input type="checkbox" onclick="toggle(this)" />
            </th>
            <th>Tên sản phẩm </th>
            <th>@Html.DisplayNameFor(model => model.First().Soluong)</th>
            <th>@Html.DisplayNameFor(model => model.First().Ngayketthuc)</th>
            <th>@Html.DisplayNameFor(model => model.First().Ngaydang)</th>
            <th>@Html.DisplayNameFor(model => model.First().Mota)</th>
            <th>Hành động</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <input type="checkbox" name="lstdel" value="@item.ID" />
                </td>
                <td class="center">@item.SanPham.TenSP</td>
                <td class="center">@item.Soluong</td>
                <td class="center">@item.Ngayketthuc</td>
                <td class="center">@item.Ngaydang</td>
                <td class="center">@Html.Raw(item.Mota)</td>
                <td class="center">
                    <a class="btn btn-info" href="@Url.Action("EditSPCM", "SanPhamCanMua", new { id = item.ID })">
                        <i class="glyphicon glyphicon-edit icon-white"></i>
                        Sửa
                    </a>
                    <a class="btn btn-danger" href='javascript:XoaItem("@Url.Action("DeleteSPCM", "SanPhamCanMua")","@item.ID")'>
                        <i class="glyphicon glyphicon-trash icon-white"></i>
                        Xóa
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="pagination-holder">
    <div class="row">
        <div class="col-xs-12 col-sm-6 text-left">
            <div id="nav_grid">
                @Html.PagedListPager(Model, page => Url.Action("TimHangSX", "HangSX", new { key = @ViewBag.key, page = page }))
            </div>
        </div>
        <div class="col-xs-12 col-sm-6">
            <div class="result-counter">
                Có tât cả <span>@Model.TotalItemCount</span> dòng
            </div>
        </div>
    </div><!-- /.row -->
</div><!-- /.pagination-holder -->