EC-TH2012-J/Models/NhaCungCap.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC_TH2012_J.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaCungCap()
        {
            this.HopDongNCCs = new HashSet<HopDongNCC>();
            this.Oauths = new HashSet<Oauth>();
            this.ConfigAPIs = new HashSet<ConfigAPI>();
            this.DanhsachdangkisanphamNCCs = new HashSet<DanhsachdangkisanphamNCC>();
        }
    
        public string MaNCC { get; set; }
        public string TenNCC { get; set; }
        public string DiaChi { get; set; }
        public string SDT_NCC { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Net_user { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDongNCC> HopDongNCCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oauth> Oauths { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfigAPI> ConfigAPIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhsachdangkisanphamNCC> DanhsachdangkisanphamNCCs { get; set; }
    }
}

EC-TH2012-J/Controllers/B2B/NhaCungCapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EC_TH2012_J.Models;
using EC_TH2012_J.Models.B2B;
using PagedList;
using PagedList.Mvc;

namespace EC_TH2012_J.Controllers.B2B
{
    public class NhaCungCapController : Controller
    {
        //
        // nha cung cap
        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public ActionResult SearchByName(string term)
        {
            NhaCungCapModel sp = new NhaCungCapModel();
            IQueryable<NhaCungCap> lst = sp.TimNCC(term);
            var splist = (from p in lst orderby p.TenNCC descending select new { p.MaNCC, p.TenNCC }).Take(5);
            return Json(splist, JsonRequestBehavior.AllowGet);
        }

        public ActionResult TimNCC(string key, int? page)
        {
            NhaCungCapModel ncc = new NhaCungCapModel();
            ViewBag.key = key;
            return PhanTrangNCC(ncc.TimNCC(key).Where(m=>!string.IsNullOrEmpty(m.Net_user)), page, null);
        }

        public ActionResult PhanTrangNCC(IQueryable<NhaCungCap> lst, int? page, int? pagesize)
        {
            int pageSize = (pagesize ?? 10);
            int pageNumber = (page ?? 1);
            return PartialView("NCCPartial", lst.OrderBy(m => m.TenNCC).ToPagedList(pageNumber, pageSize));
        }

      
	}
}

EC-TH2012-J/Views/NhaCungCap/Index.cshtml
@model EC_TH2012_J.Models.NhaCungCap
@{
    ViewBag.Title = "Nhà cung cấp";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2><i class="glyphicon glyphicon-user"></i>@ViewBag.Title</h2>
                <div class="box-icon">
                    <a href="#" class="btn btn-setting btn-round btn-default"><i class="glyphicon glyphicon-cog"></i></a>
                    <a href="#" class="btn btn-minimize btn-round btn-default">
                        <i class="glyphicon glyphicon-chevron-up"></i>
                    </a>
                    <a href="#" class="btn btn-close btn-round btn-default"><i class="glyphicon glyphicon-remove"></i></a>
                </div>
            </div>
            <div class="box-content">
                <div class="alert alert-info" id="alert-info" style="display:none"></div>
                <div class="form-inline" style="text-align: right; padding: 10px">

                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-search red"></i></span>
                        <input id="inputIcon" type="text" class="form-control" placeholder="Nhập tên nhà cung cấp" oninput="timkiemncc()">
                    </div>
                </div>
                <div class="Ajax-Table">
                    @Html.Action("TimNCC", "NhaCungCap")
                </div>

            </div>
        </div>
    </div>
    <!--/span-->
</div><!--/row-->

EC-TH2012-J/Views/NhaCungCap/NCCPartial.cshtml
@using EC_TH2012_J.Models;
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<NhaCungCap>


<table class="table table-striped table-bordered bootstrap-datatable datatable responsive">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.First().TenNCC)</th>
            <th>@Html.DisplayNameFor(model => model.First().DiaChi)</th>
            <th>@Html.DisplayNameFor(model => model.First().SDT_NCC)</th>
            <th>@Html.DisplayNameFor(model => model.First().Email)</th>
            <th>@Html.DisplayNameFor(model => model.First().Website)</th>
            <th>Tên đăng nhập</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>              
                <td class="center">@item.TenNCC</td>
                <td class="center">@item.DiaChi</td>
                <td class="center">@item.SDT_NCC</td>
                <td class="center">@item.Email</td>
                <td class="center">@item.Website</td>
                @if(string.IsNullOrEmpty(@item.Net_user))
                {
                    <td class="center">@String.Empty</td>
                }
                else
                {
                    <td class="center">@item.AspNetUser.UserName</td>
                }
                    
                
            </tr>
        }
    </tbody>
</table>

<div class="pagination-holder">
    <div class="row">
        <div class="col-xs-12 col-sm-6 text-left">
            <div id="nav_grid">
                @Html.PagedListPager(Model, page => Url.Action("TimNCC", "NhaCungCap", new { key = @ViewBag.key, page = page }))
            </div>
        </div>
        <div class="col-xs-12 col-sm-6">
            <div class="result-counter">
                Có tât cả <span>@Model.TotalItemCount</span> dòng
            </div>
        </div>
    </div><!-- /.row -->
</div><!-- /.pagination-holder -->