EC-TH2012-J/Controllers/B2B/AuctionController.cs
using EC_TH2012_J.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EC_TH2012_J.Controllers.B2B
{
    public class AuctionController : Controller
    {
        // GET: Auction
        [AuthLog(Roles = "Quản trị viên,Nhân viên,Nhà cung cấp")]
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Danhsachcanmua()
        {
            SanphamcanmuaModel sp = new SanphamcanmuaModel();
            var temp = sp.getDS(0, 5);
            return View(temp);        
        }
        public ActionResult ProductFilterB2B()
        {
            CategoryModel cat = new CategoryModel();
            return View(cat.GetCategory());
        }
        public ActionResult ChitietAuction(Sanphamcanmua a)
        {
            SanphamcanmuaModel sp = new SanphamcanmuaModel();
            a.SanPham = sp.getSP(a.MaSP);
            return View(a);
        }
        public ActionResult ChitietSanphamAuction(int spcm)
        {
            SanphamcanmuaModel spmodel = new SanphamcanmuaModel();
            Sanphamcanmua temp = spmodel.getSanphamcanmua(spcm);
            temp.SanPham = spmodel.getSP(temp.MaSP);
            return View(temp);
        }
        public ActionResult ModalRegister(int ID)
        {
            DangkisanphamModel model = new DangkisanphamModel();
            var temp = model.createDangKiSanPham(User.Identity.Name,ID);
            return View(temp);
        }
        [HttpPost]
        public ActionResult RegisterProduct(DangkisanphamModel a)
        {
            if(new DangkisanphamModel().ThemDanhKi(a))
            {
                Session["TB"] = true;
            }
            else
            {
                Session["TB"] = false;
            }

            return RedirectToAction("ChitietSanphamAuction", new { spcm = a.MaSPCM });
        }
        public ActionResult DanhsachNCCDK(int IDSPCM)
        {
            var ds = new DangkisanphamModel().getDSDKNCC(IDSPCM);
            return View(ds);
        }
        public ActionResult Hopdong()
        {
            return View();
        }
    }
}

EC-TH2012-J/Views/Auction/ChitietAuction.cshtml
@model EC_TH2012_J.Models.Sanphamcanmua
<div class="product-item">
    @*<div class="ribbon red"><span>sale</span></div>*@
    @*@if (Model.isnew == true)
    {
        <div class="ribbon blue"><span>Mới nhập</span></div>
    }
    @if (Model.ishot == true)
    {
        <div class="ribbon red"><span>Hot</span></div>
    }*@
    @*<div class="ribbon blue"><span>new!</span></div>*@
    @*<div class="ribbon green"><span>bestseller</span></div>*@
        <div class="image">
            <img alt="" src="@Url.Content("~/template/assets/images/blank.gif")" data-echo="@Url.Content("~/images/products/")@Model.SanPham.AnhDaiDien" />
        </div>
        <div class="body">
            <div class="label-discount clear"></div>
            @*<div class="label-discount green">Giảm 50%</div>*@
            <div class="title">
                <a href="@Url.Action("ChitietSanphamAuction", "Auction", new { spcm = Model.ID })">@Model.SanPham.TenSP</a>
            </div>
            <div class="brand">@Model.SanPham.HangSX</div>
            <div class="countdowns">
                <div data-countdown="@Model.Ngayketthuc"></div>
            </div>
        </div>
        <div class="soluong">
           Số lượng cần :  @Model.Soluong       
        </div>
        <div class="hover-area">
            <div class="add-cart-button">
                @if (User.Identity.IsAuthenticated)
                {
                    <a href="@Url.Action("ChitietSanphamAuction", "Auction", new { spcm = Model.ID })" class="le-button">Xem Chi Tiết</a>
                }
                else
                {
                    <a href="@Url.Action("Authentication","Account")" class="le-button">Xem Chi Tiết</a>
                }
            </div>
            <div class="wish-compare">
                <a class="btn-add-to-wishlist" href="#">Yêu thích</a>
                <a class="btn-add-to-compare" href="#">So sánh</a>
            </div>
        </div>
    </div><!-- /.product-item -->

EC-TH2012-J/Views/Auction/ChitietSanphamAuction.cshtml
@model EC_TH2012_J.Models.Sanphamcanmua
@{
    ViewBag.Title = "Chi tiết sản phẩm đấu giá";
    Layout = "~/Views/Shared/_LayoutB2B.cshtml";
    ViewBag.TB = Session["TB"];
    Session["TB"] = null;
}
<script type="text/javascript">
    $(document).ready(function()
    {
        if("@ViewBag.TB" != "")
        {
            if("@ViewBag.TB" == "True")
            {
                alert("Đăng kí bạn đã được lưu lại. Xin cảm ơn đã đăng kí");
            }
            else
            {
                alert("Đăng kí bị lỗi");
            }
        }
    });
</script>
<script language="javascript" type="text/javascript">
    $(document).ready(function () {
        
        $(document).on("click", "#nav a[href]", function () {
            $.ajax({
                url: $(this).attr("href"),
                type: 'GET',
                cache: false,
                success: function (result) {
                    $('#Comments').html(result);
                    $('html, body').animate({
                        scrollTop: $("#reviews").offset().top
                    }, 500);
                }
            });
            return false;
        });

    });
</script>

<div id="single-product">
    <div class="container">
        <div class="no-margin col-xs-12 col-sm-6 col-md-5 gallery-holder">
            <div class="product-item-holder size-big single-product-gallery small-gallery">
                <div id="owl-single-product">
                    <div class="single-product-gallery-item" id="slide1">
                        <a data-rel="prettyphoto" href="@Url.Content("~/images/products/")@Model.SanPham.AnhDaiDien">
                            <img class="img-responsive" alt="" src="@Url.Content("~/template/")assets/images/blank.gif" data-echo="@Url.Content("~/images/products/")@Model.SanPham.AnhDaiDien" width="353" />
                        </a>
                    </div><!-- /.single-product-gallery-item -->
                    <div class="single-product-gallery-item" id="slide2">
                        <a data-rel="prettyphoto" href="@Url.Content("~/images/products/")@Model.SanPham.AnhNen">
                            <img class="img-responsive" alt="" src="@Url.Content("~/template/")assets/images/blank.gif" data-echo="@Url.Content("~/images/products/")@Model.SanPham.AnhNen" />
                        </a>
                    </div><!-- /.single-product-gallery-item -->
                    <div class="single-product-gallery-item" id="slide3">
                        <a data-rel="prettyphoto" href="@Url.Content("~/images/products/")@Model.SanPham.AnhKhac">
                            <img class="img-responsive" alt="" src="@Url.Content("~/template/")assets/images/blank.gif" data-echo="@Url.Content("~/images/products/")@Model.SanPham.AnhKhac" />
                        </a>
                    </div><!-- /.single-product-gallery-item -->
                </div><!-- /.single-product-slider -->

                <div class="single-product-gallery-thumbs gallery-thumbs">
                    <div id="owl-single-product-thumbnails">
                        <a class="horizontal-thumb active" data-target="#owl-single-product" data-slide="0" href="#slide1">
                            <img width="67" alt="" src="@Url.Content("~/template/")assets/images/blank.gif" data-echo="@Url.Content("~/images/products/")@Model.SanPham.AnhDaiDien" />
                        </a>
                        <a class="horizontal-thumb" data-target="#owl-single-product" data-slide="1" href="#slide2">
                            <img width="67" alt="" src="@Url.Content("~/template/")assets/images/blank.gif" data-echo="@Url.Content("~/images/products/")@Model.SanPham.AnhNen" />
                        </a>
                        <a class="horizontal-thumb" data-target="#owl-single-product" data-slide="2" href="#slide3">
                            <img width="67" alt="" src="@Url.Content("~/template/")assets/images/blank.gif" data-echo="@Url.Content("~/images/products/")@Model.SanPham.AnhKhac" />
                        </a>
                    </div><!-- /#owl-single-product-thumbnails -->
                    @*<div class="nav-holder left hidden-xs">
                            <a class="prev-btn slider-prev" data-target="#owl-single-product-thumbnails" href="#prev"></a>
                        </div><!-- /.nav-holder -->

                        <div class="nav-holder right hidden-xs">
                            <a class="next-btn slider-next" data-target="#owl-single-product-thumbnails" href="#next"></a>
                        </div><!-- /.nav-holder -->*@
                </div><!-- /.gallery-thumbs -->
            </div><!-- /.single-product-gallery -->
        </div><!-- /.gallery-holder -->
        <div class="no-margin col-xs-12 col-sm-7 body-holder">
            <div class="body">
                @*<div class="star-holder inline"><div class="star" data-score="4"></div></div>*@
                
                <div class="title"><a href="#">@Model.SanPham.TenSP</a></div>
                <div class="brand"></div>
                <div class="social-row">
                    <span class="st_facebook_hcount"></span>
                    <span class="st_twitter_hcount"></span>
                    <span class="st_pinterest_hcount"></span>
                </div>
                <div class="buttons-holder">
                    <label>Chia sẻ với bạn bè</label>
                </div>
                <div class="brand"></div>
                <div class="excerpt">
                    <p class="text-capitalize">Nội dung khuyến mãi </p>
                </div>
                <div class="brand"></div>
                <div class="countdowns countdownsct">
                    <div data-countdown="@Model.Ngayketthuc"></div>
                </div>
                <div class="qnt-holder">
                    <div class="soluongct">
                        Số lượng cần :  @Model.Soluong
                    </div>
                    <a id="addto-cart" href="javascript:;" class="le-button huge" data-toggle="modal" data-target="#myModal">Đăng kí</a>
                </div><!-- /.qnt-holder -->
            </div><!-- /.body -->
        </div><!-- /.body-holder -->
    </div><!-- /.container -->
</div><!-- /.single-product -->
<!-- ========================================= SINGLE PRODUCT TAB ========================================= -->
<section id="single-product-tab">
    <div class="container">
        <div class="tab-holder">

            <ul class="nav nav-tabs simple">
                <li class="active"><a href="#description" data-toggle="tab">Mô tả</a></li>
                <li><a href="#additional-info" data-toggle="tab">Thông sô kỹ thuật</a></li>
                <li><a href="#additional-Register" data-toggle="tab">Các nhà cung cấp đã đăng kí</a></li>
                <li><a href="#reviews" data-toggle="tab">Bình luận</a></li>
            </ul><!-- /.nav-tabs -->
            <div class="tab-content">
                <div class="tab-pane active" id="description">
                    <p>@Html.Raw(Model.Mota)</p>
                    
                </div><!-- /.tab-pane #description -->
                <div class="tab-pane" id="additional-info">
                    <h2>Thông số kỹ thuật của @Model.SanPham.TenSP</h2>
                    @Html.Action("ThongSoKyThuat", "SanPham", new { MaSP = Model.MaSP })
                </div><!-- /.tab-pane #additional-info -->
                <div class="tab-pane" id="additional-Register">
                    <h2>Các nhà cung cấp đã đăng kí bán @Model.SanPham.TenSP</h2>
                    @Html.Action("DanhsachNCCDK", "Auction", new { IDSPCM = Model.ID })
                    
                </div><!-- /.tab-pane #additional-info -->

                <div class="tab-pane" id="reviews">
                    <div class="comments" id="Comments">
                        @*@Html.Action("LoadComment", "Comment", new RouteValueDictionary { { "masp", @Model.MaSP } })*@
                    </div><!-- /.comments -->
                    <div class="add-review row">
                        <div class="col-sm-8 col-xs-12">
                            <div class="new-review-form">
                                @*@Html.Action("AddComment", "Comment", new RouteValueDictionary { { "masp", @Model.MaSP } })*@
                            </div><!-- /.new-review-form -->
                        </div><!-- /.col -->
                    </div><!-- /.add-review -->
                </div><!-- /.tab-pane #reviews -->
            </div><!-- /.tab-content -->
        </div><!-- /.tab-holder -->
    </div><!-- /.container -->
</section><!-- /#single-product-tab -->
<!-- ========================================= SINGLE PRODUCT TAB : END ========================================= -->
<!-- ========================================= SAN PHAM LIEN QUAN ========================================= -->
<!-- /#recently-reviewd -->
@*@Html.Action("Loadsplienquan", "SanPham", new { maloai = @Model.LoaiSP, sl = 6 });*@
<!-- ========================================= RECENTLY VIEWED : END ========================================= -->

@Html.Action("ModalRegister", "Auction", new { ID = Model.ID})

EC-TH2012-J/Views/Auction/DanhsachNCCDK.cshtml
@model List<EC_TH2012_J.Models.DanhsachdangkisanphamNCC>

<div class="row">
    @for (int i = 0; i < Model.Count; i++)
    {
        <div class="row">
            <div class="col-md-3">
                <img src="~/images/avatars/3a92095d-9524-4310-91db-e4b33f34d077.jpg" alt="Hình đại diện" />
            </div>
            <div class="col-md-9">
                <a href="#">@Model[i].TenNCC</a>
                <p>
                    <i>Ngày Đăng Kí :</i>
                    <span>@String.Format("{0:d/M/yyyy HH:mm:ss}", @Model[i].NgayDK)</span>
                </p>
            </div>
        </div>
    }
</div>

EC-TH2012-J/Views/Auction/Danhsachcanmua.cshtml
@model System.Collections.Generic.List<EC_TH2012_J.Models.Sanphamcanmua>

<div class="product-grid-holder">
    <div class="row no-margin">
        @foreach (var item in Model)
        {
            <div class="col-xs-12 col-sm-4 no-margin product-item-holder hover">
                @Html.Action("ChitietAuction", "Auction", new { a = item})
            </div><!-- /.product-item-holder -->
        }
    </div><!-- /.row -->
</div><!-- /.product-grid-holder -->

EC-TH2012-J/Views/Auction/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutB2B.cshtml";
}

<section id="gaming">
    <div class="grid-list-products">
        <h2 class="section-title">Danh sách sản phẩm cần mua</h2>

        <div class="control-bar">
            @*Chưa code phần sort*@
            <div id="popularity-sort" class="le-select">
                <select data-placeholder="sort by popularity">
                    <option value="1">Sắp xếp theo loại</option>
                    <option value="2">Sắp xếp theo hãng</option>
                    <option value="3">Sắp xếp theo giá</option>
                </select>
            </div>

            <div id="item-count" class="le-select">
                <select>
                    <option value="1">Tăng dần</option>
                    <option value="2">Giảm dần</option>
                </select>
            </div>
            <div class="grid-list-buttons">
                <ul>
                    <li class="grid-list-button-item active"><a data-toggle="tab" href="#grid-view"><i class="fa fa-th-large"></i> Lưới</a></li>
                    <li class="grid-list-button-item "><a data-toggle="tab" href="#list-view"><i class="fa fa-th-list"></i> Dánh sách</a></li>
                </ul>
            </div>
        </div><!-- /.control-bar -->
        <div id="grid-view" class="products-grid fade tab-pane in active">
            @Html.Action("Danhsachcanmua", "Auction")
        </div><!-- /.products-grid #grid-view -->
        <div class="tab-content">
            
        </div><!-- /.tab-content -->
    </div><!-- /.grid-list-products -->
</section><!-- /#gaming -->

EC-TH2012-J/Views/Auction/ModalRegister.cshtml
@model  EC_TH2012_J.Models.DangkisanphamModel
<div class="modal fade" tabindex="-1" role="dialog" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Đăng kí bán sản phẩm</h4>
            </div>
            @using (Html.BeginForm("RegisterProduct", "Auction", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                <div class="modal-body">
                    <div class="form-group">
                        @Html.HiddenFor(m=>m.MaSPCM)
                        @Html.Label("Tên sản phẩm", new { @class = "col-md-4 control-label" })
                        <div class="col-md-8">
                            @Html.TextBoxFor(m => m.tenSanPham, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.HiddenFor(m => m.MaNCC)
                        @Html.Label("Nhà Cung Cấp", new { @class = "col-md-4 control-label" })
                        <div class="col-md-8">
                            @Html.TextBoxFor(m => m.tenNhaCC, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.Label("Tiền mỗi sản phẩm*(Đồng)", new { @class = "col-md-4 control-label" })
                        <div class="col-md-8">
                            @Html.TextBoxFor(m => m.TienmoiSP, new { @class = "form-control", @type = "number", @required = "required" })
                            @Html.ValidationMessageFor(m=>m.TienmoiSP)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.Label("Ghi chú", new { @class = "col-md-4 control-label" })
                        <div class="col-md-8">
                            @Html.TextAreaFor(m => m.Ghichu, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            }
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

EC-TH2012-J/Views/Auction/ProductFilterB2B.cshtml
<script>
    //$(document).ready(function () {
    //    $(document).on("click", "#nav_grid a[href]", function () {
    //        $.ajax({
    //            url: $(this).attr("href"),
    //            type: 'GET',
    //            cache: false,
    //            success: function (result) {
    //                $('#grid-view').html(result);
    //                $('html, body').animate({
    //                    scrollTop: $("#grid-view").offset().top
    //                }, 500);
    //            }
    //        });
    //        return false;
    //    });
    //});

    function summitfilter()
    {
        var form = document.getElementById("productfilterfrm");
        form.submit();
    }

</script>

<!-- ========================================= PRODUCT FILTER ========================================= -->
@model IQueryable<EC_TH2012_J.Models.LoaiSP>
@using EC_TH2012_J.Models;
<div class="widget">
    <h1>Lọc sản phẩm</h1>
    <form id="productfilterfrm" action="@Url.Action("AdvancedSearchView", "Search")" autocomplete="off">
        <div class="body bordered">
            <div class="category-filter">
                <h2>Loại</h2>
                <hr>
                <h5>Loại sản phẩm</h5>
                <ul>
                    @{
                        foreach (var item in Model)
                        {
                            <li><input name="loai" class="le-checkbox" type="radio" value="@item.MaLoai" /> <label>@item.TenLoai</label></li>
                        }
                    }
                </ul>
            </div><!-- /.category-filter -->
        </div><!-- /.body -->
    </form>
</div><!-- /.widget -->
<!-- ========================================= PRODUCT FILTER : END ========================================= -->