EC-TH2012-J/Controllers/B2B/DanhSachDKController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using EC_TH2012_J.Models;
using EC_TH2012_J.Models.B2B;


namespace EC_TH2012_J.Controllers.B2B
{
    public class DanhSachDKController : Controller
    {
        // GET: DanhSachDK
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult TimDS(string tensp, string tenncc, int? tt, int? page)
        {
            DSDangKyModel DSDK = new DSDangKyModel();
            ViewBag.tensp = tensp;
            ViewBag.tenncc = tenncc;
            ViewBag.tt = tt;
            return PhanTrangDSDK(DSDK.TimDS(tensp,tenncc,tt), page, null);
        }

        [HttpPost]
        public ActionResult KyHopDong(string id)
        {
            SanphamcanmuaModel sp = new SanphamcanmuaModel();
            sp.DeleteSPCM(Convert.ToInt32(id));
            return TimDS(null, null, null, null);

        }

        public ActionResult DeleteDSDK(int id)
        {
            DSDangKyModel ncc = new DSDangKyModel();
            if (ncc.Findbyid(id) == null)
            {
                return HttpNotFound();
            }
            ncc.DeleteDSDK(id);
            return TimDS(null, null,null,null);
        }

        [HttpPost]
        public ActionResult MultibleDel(List<string> lstdel)
        {
            foreach (var item in lstdel)
            {
                DSDangKyModel ncc = new DSDangKyModel();
                ncc.DeleteDSDK(Convert.ToInt32(item));
            }
            return TimDS(null, null, null, null);
        }

        public ActionResult PhanTrangDSDK(IQueryable<DanhsachdangkisanphamNCC> lst, int? page, int? pagesize)
        {
            int pageSize = (pagesize ?? 10);
            int pageNumber = (page ?? 1);
            return PartialView("DSDKPartial", lst.OrderByDescending(m => m.NgayDK).ToPagedList(pageNumber, pageSize));
        }
    }
}

EC-TH2012-J/Views/DanhSachDK/DSDKPartial.cshtml
@using EC_TH2012_J.Models;
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<DanhsachdangkisanphamNCC>


<table class="table table-striped table-bordered bootstrap-datatable datatable responsive">
    <thead>
        <tr>
            <th>
                <input type="checkbox" onclick="toggle(this)" />
            </th>
            <th>Tên sản phẩm </th>
            <th>Tên nhà cung cấp</th>
            <th>Ngày đăng ký</th>
            <th>Đơn giá</th>
            <th>Trạng thái</th>
            <th>Hành động</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <input type="checkbox" name="lstdel" value="@item.ID" />
                </td>
                <td class="center">@item.Sanphamcanmua.SanPham.TenSP</td>
                <td class="center">@item.NhaCungCap.TenNCC</td>
                <td class="center">@item.NgayDK</td>
                <td class="center">@item.TienmoiSP</td>
                <td class="center">
                    @if (item.Trangthai == 0)
                    { <span class="label label-info">Chưa duyệt</span> }
                    else if (item.Trangthai == 1)
                    { <span class="label label-success">Đã ký hợp đồng</span> }
                    else
                    {<span class="label label-info">Không chấp nhận</span>}
            </td>
            <td class="center"> 
                
                <a class="btn btn-success" href='javascript:KyHopDong("@item.Sanphamcanmua.MaSP","@item.MaNCC",@item.MaSPCanMua)'>
                    <i class="glyphicon glyphicon-ok icon-white"></i>
                    Ký hợp đồng
                </a>

                <a class="btn btn-danger" href='javascript:XoaItem("@Url.Action("DeleteDSDK", "DanhSachDK")",@item.ID)'>
                    <i class="glyphicon glyphicon-trash icon-white"></i>
                    Xóa
                </a>
            </td>
        </tr>
        }
    </tbody>
</table>

<div class="pagination-holder">
    <div class="row">
        <div class="col-xs-12 col-sm-6 text-left">
            <div id="nav_grid">
                @Html.PagedListPager(Model, page => Url.Action("TimHangSX", "HangSX", new { key = @ViewBag.key, page = page }))
            </div>
        </div>
        <div class="col-xs-12 col-sm-6">
            <div class="result-counter">
                Có tât cả <span>@Model.TotalItemCount</span> dòng
            </div>
        </div>
    </div><!-- /.row -->
</div><!-- /.pagination-holder -->

EC-TH2012-J/Views/DanhSachDK/Index.cshtml
@model EC_TH2012_J.Models.HopDongNCC
@{
    ViewBag.Title = "Danh sách đăng ký cung cấp sản phẩm";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<script>
    function KyHopDong(masp, mancc, maspcm) {
        $('#nhacungcap').val(mancc);
        $('#sanpham').val(masp);
        $('#maspcm').val(maspcm);
        $('html, body').animate({
            scrollTop: $("#nhacungcap").offset().top
        }, 500);
    }

    function updatespcm() {
        var value = $('#maspcm').val();
        $.ajax({
            url: '@Url.Action("KyHopDong","DanhSachDK")',
            type: 'POST',
            data: { id: value },
            success: function (result) {
                $('.Ajax-Table').html(result);
                alert("Ky hop dong xong")
            },
        });
    }
</script>


<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2><i class="glyphicon glyphicon-user"></i>@ViewBag.Title</h2>
                <div class="box-icon">
                    <a href="#" class="btn btn-setting btn-round btn-default"><i class="glyphicon glyphicon-cog"></i></a>
                    <a href="#" class="btn btn-minimize btn-round btn-default">
                        <i class="glyphicon glyphicon-chevron-up"></i>
                    </a>
                    <a href="#" class="btn btn-close btn-round btn-default"><i class="glyphicon glyphicon-remove"></i></a>
                </div>
            </div>
            <div class="box-content">
                <div class="alert alert-info" id="alert-info" style="display:none"></div>
                <div class="form-inline" style="text-align: right; padding: 10px">

                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-search red"></i></span>
                        <input id="tenncc" type="text" class="form-control" placeholder="Tên nhà cung cấp" oninput="timkiemdsdk()">
                    </div>

                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-search red"></i></span>
                        <input id="tensp" type="text" class="form-control" placeholder="Tên sản phẩm" oninput="timkiemdsdk()">
                    </div>
                    <div class="input-group">
                        <a class="btn btn-danger" href='javascript:multibledel("@Url.Action("MultibleDel", "DanhSachDK")")'>
                            <i class="glyphicon glyphicon-trash icon-white"></i>
                            Xóa các đăng ký đã chọn
                        </a>
                    </div>

                </div>
                <div class="Ajax-Table">
                    @Html.Action("TimDS", "DanhSachDK")
                </div>

            </div>
        </div>
    </div>
    <!--/span-->
</div><!--/row-->

<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2><i class="glyphicon glyphicon-user"></i>Ký hợp đồng</h2>
                <div class="box-icon">
                    <a href="#" class="btn btn-setting btn-round btn-default"><i class="glyphicon glyphicon-cog"></i></a>
                    <a href="#" class="btn btn-minimize btn-round btn-default">
                        <i class="glyphicon glyphicon-chevron-up"></i>
                    </a>
                    <a href="#" class="btn btn-close btn-round btn-default"><i class="glyphicon glyphicon-remove"></i></a>
                </div>
            </div>
            <div class="box-content">
                <input type="hidden" id="maspcm" />
                @using (Ajax.BeginForm("ThemHopDong", "HopDong", null, new AjaxOptions { HttpMethod = "POST", OnSuccess = "updatespcm" }, new { autocomplete = "off", enctype = "multipart/form-data" }))
                {

                    <div class="form-horizontal">
                        <div class="alert alert-info" style="display:none">
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary()
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.MaNCC, new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.TextBoxFor(model => model.MaNCC, new { @class = "form-control", id = "nhacungcap", required = "required", @readonly="readonly" })
                                @Html.ValidationMessageFor(model => model.MaNCC)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.NgayKy, new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                <input class="form-control text-box single-line valid" data-val="true" data-val-date="The field NgayKy must be a date." id="NgayKy" name="NgayKy" type="date" value="" aria-invalid="false" aria-describedby="NgayKy-error">
                                @Html.ValidationMessageFor(model => model.NgayKy)
                            </div>
                        </div>


                        <div class="form-group">
                            @Html.LabelFor(model => model.ThoiHanHD, new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.EditorFor(model => model.ThoiHanHD, new { htmlAttributes = new { @class = "form-control", required = "required", @type = "number" } })
                                @Html.ValidationMessageFor(model => model.ThoiHanHD)

                            </div>
                        </div>


                        <div class="form-group">
                            @Html.LabelFor(model => model.MaSP, new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.TextBoxFor(model => model.MaSP, new { @class = "form-control", id = "sanpham", required = "required", @readonly = "readonly" })
                                @Html.ValidationMessageFor(model => model.MaSP)

                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.SLToiThieu, new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.EditorFor(model => model.SLToiThieu, new { htmlAttributes = new { @class = "form-control", required = "required", @type = "number" } })
                                @Html.ValidationMessageFor(model => model.SLToiThieu)
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.SLCungCap, new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.EditorFor(model => model.SLCungCap, new { htmlAttributes = new { @class = "form-control", required = "required", @type = "number" } })
                                @Html.ValidationMessageFor(model => model.SLCungCap)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.DonGia, new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.EditorFor(model => model.DonGia, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                                @Html.ValidationMessageFor(model => model.DonGia)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.SoNgayGiao, new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.EditorFor(model => model.SoNgayGiao, new { htmlAttributes = new { @class = "form-control", required = "required", @type = "number" } })
                                @Html.ValidationMessageFor(model => model.SoNgayGiao)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.IsBuy, new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.DropDownList("IsBuy", new SelectList(new List<object>
                            {
                                new { value = true , text = "Hợp đồng mua"  },
                                new { value = false , text = "Hợp đồng bán" },
                            }, "value", "text", true), new { @class = "form-control", @readonly = "readonly", value = "true" })
                                @Html.ValidationMessageFor(model => model.IsBuy)
                            </div>
                        </div>



                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Thêm mới" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }

            </div>

        </div>
    </div>
    <!--/span-->
</div><!--/row-->